org: yura703
app: product-service
service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-jest-plugin  

package:
  individually: true

custom: 
  webpack: 
    webpackConfig:  'webpack.config.js'  # Имя файла конфигурации 
    webpack includeModules:  false  # Конфигурация модулей узла для упаковки 
    packager:  'npm'  # Packager, который будет использоваться для упаковки ваших внешних модулей 
    excludeFiles:  src/** /*.test.js  # Предоставить glob для игнорируемых файлов  
  jest:  

functions:
  getProductByID:
    handler: functions/getProductByID/getProductByID.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true

  getAllProducts:
    handler: functions/getAllProducts/getAllProducts.handler
    events:
      - http:
          path: products
          method: get
          cors: true      
