
app:  import-service
service: import-service
frameworkVersion: '3'
useDotenv: true

custom:
  bucket: yura703-task5

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1 
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::yura703-task5"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::yura703-task5/*"
          
plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-jest-plugin 

package:
  individually: true

custom: 
  webpack: 
    webpackConfig:  'webpack.config.js'  # Имя файла конфигурации 
    webpack includeModules:  false  # Конфигурация модулей узла для упаковки 
    packager:  'npm'  # Packager, который будет использоваться для упаковки ваших внешних модулей 
    excludeFiles:  src/** /*.test.js  # Предоставить glob для игнорируемых файлов  
  jest:  

functions:
  importProductsFile:
    handler: functions/importProductsFile.handler
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: functions/importFileParser.handler
    events:
      - s3: 
        bucket: yura703-task5
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
          - suffix: .csv 
        existing: true         
  
  
  