
app:  import-service
service: import-service
frameworkVersion: '3'
useDotenv: true

custom:
  bucketName: yura703-task5
  jest:

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1 
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - arn:aws:s3:::yura703-task5
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::yura703-task5/*

plugins:
  - serverless-jest-plugin  

package:
  individually: true

functions:
  importProductsFile:
    handler: functions/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: functions/importFileParser.importFileParser
    events:
      - s3: 
        bucket: yura703-task5
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
        existing: true         
  
  
  